### ISSUE TITLE
It seems like that the kld of vae+nf tends to be lower than zero?

### ISSUE THREAD

**Issue by limingzhan0904** [ex4sperans/variational-inference-with-normalizing-flows#1]
Hi, I find out that the p(z_k| x)||p(z_K) can be lower than 0. Is this reasonable?

**Comment by ex4sperans** [comment]
Hi, I didn't include constant terms to the KL expression, so it's absolutely OK. Apparently, I should include them to avoid the confusion, thank you.

**Comment by limingzhan0904** [comment]
@ex4sperans thank you for your reply. I also think it is because we do not include the free bits constant. But I have no clue about How the KLD can be lower than zero in the first place if we have a real KLD. This confuses me a lot, do you have any idea?
